import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./stories/component/sidebar";
import Header from "./stories/component/header";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "StoryKu",
	description: "Generated by create next app",
	icons: "/favicon.ico",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="flex">
					<Sidebar />
					<main className="flex-1 bg-gray-100 min-h-screen">
						<Header />
						<div className="p-5">{children}</div>
					</main>
				</div>
			</body>
		</html>
	);
}
